# Generated by Django 4.2.30 on 2026-06-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaultasset',
            name='metadata_encrypted',
            field=models.TextField(blank=True),
        ),
    ]
