# Generated by Django 4.2.30 on 2026-06-11 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiaries', '0001_initial'),
        ('vault', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeathVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('death_certificate', models.FileField(upload_to='death_certificates/%Y/%m/%d/')),
                ('obituary_link', models.URLField(blank=True)),
                ('additional_notes', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_verifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='death_verifications', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_deaths', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'death_verifications',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='InheritanceRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=255, unique=True)),
                ('accessed_at', models.DateTimeField(blank=True, null=True)),
                ('access_expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'inheritance_releases',
            },
        ),
        migrations.CreateModel(
            name='LegacyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'legacy_plans',
            },
        ),
        migrations.CreateModel(
            name='InheritanceReleaseAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decrypted_username', models.TextField(blank=True)),
                ('decrypted_password', models.TextField(blank=True)),
                ('decrypted_notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vault.vaultasset')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legacy.inheritancerelease')),
            ],
            options={
                'db_table': 'inheritance_release_assets',
            },
        ),
        migrations.AddField(
            model_name='inheritancerelease',
            name='assets',
            field=models.ManyToManyField(through='legacy.InheritanceReleaseAsset', to='vault.vaultasset'),
        ),
        migrations.AddField(
            model_name='inheritancerelease',
            name='beneficiary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiaries.beneficiary'),
        ),
        migrations.AddField(
            model_name='inheritancerelease',
            name='verification',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='release', to='legacy.deathverification'),
        ),
        migrations.CreateModel(
            name='InactivityCheckLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('days_inactive', models.PositiveIntegerField()),
                ('warning_sent', models.BooleanField(default=False)),
                ('escalation_sent', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inactivity_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inactivity_check_logs',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='LegacyPlanAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vault.vaultasset')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiaries.beneficiary')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='legacy.legacyplan')),
            ],
            options={
                'db_table': 'legacy_plan_assignments',
                'unique_together': {('plan', 'beneficiary', 'asset')},
            },
        ),
    ]
