# Generated by Django 4.2.30 on 2026-06-11 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beneficiaries', '0001_initial'),
        ('legacy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InheritanceDeliveryTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('bounced', 'Bounced'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_delivered_at', models.DateTimeField(blank=True, null=True)),
                ('email_opened_at', models.DateTimeField(blank=True, null=True)),
                ('email_clicked_at', models.DateTimeField(blank=True, null=True)),
                ('email_bounced_at', models.DateTimeField(blank=True, null=True)),
                ('bounce_reason', models.TextField(blank=True)),
                ('delivery_message_id', models.CharField(blank=True, max_length=255)),
                ('sms_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('bounced', 'Bounced'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('sms_sent_at', models.DateTimeField(blank=True, null=True)),
                ('sms_delivered_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_level', models.IntegerField(default=0, help_text='Highest reminder level sent (0=none, 1=L1, 2=L2, 3=L3, 4=L4)')),
                ('last_reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('next_reminder_scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('escalation_complete', models.BooleanField(default=False)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('claim_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiaries.beneficiary')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_tracking', to='legacy.inheritancerelease')),
            ],
            options={
                'db_table': 'inheritance_delivery_tracking',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.PositiveIntegerField()),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
