# Generated by Django 4.2.30 on 2026-06-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_account_deletion_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='escalation_grace_period',
            field=models.PositiveIntegerField(default=3, help_text='Days before first reminder'),
        ),
        migrations.AddField(
            model_name='user',
            name='escalation_l1_days',
            field=models.PositiveIntegerField(default=7, help_text='Days after grace for L1'),
        ),
        migrations.AddField(
            model_name='user',
            name='escalation_l2_days',
            field=models.PositiveIntegerField(default=14, help_text='Days after L1 for L2'),
        ),
        migrations.AddField(
            model_name='user',
            name='escalation_l3_days',
            field=models.PositiveIntegerField(default=30, help_text='Days after L2 for L3'),
        ),
        migrations.AddField(
            model_name='user',
            name='escalation_l4_days',
            field=models.PositiveIntegerField(default=60, help_text='Days after L3 for L4'),
        ),
    ]
