# Generated by Django 4.2.30 on 2026-06-11 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaultAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('asset_type', models.CharField(choices=[('account', 'Account / Login'), ('crypto', 'Cryptocurrency'), ('document', 'Document'), ('subscription', 'Subscription'), ('insurance', 'Insurance'), ('financial', 'Financial Account'), ('device', 'Device / Hardware'), ('social', 'Social Media'), ('other', 'Other')], default='account', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('username_encrypted', models.TextField(blank=True)),
                ('password_encrypted', models.TextField(blank=True)),
                ('notes_encrypted', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('account_number', models.CharField(blank=True, max_length=255)),
                ('institution', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vault_assets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='vault_documents/%Y/%m/%d/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vault.vaultasset')),
            ],
            options={
                'db_table': 'vault_documents',
            },
        ),
        migrations.CreateModel(
            name='AssetAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('action', models.CharField(default='view', max_length=50)),
                ('accessed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='vault.vaultasset')),
            ],
            options={
                'db_table': 'vault_access_logs',
            },
        ),
    ]
